### ISSUE TITLE
Nothing Happens Upon Submit?

### ISSUE THREAD

**Issue by JpTiger** [hatzopoulos/trillian-chat-history-converter#1]
Hi there, thanks for putting this together, this is exactly the tool I was looking for! However, I've put this in an XAMMP server, tried uploading an xml file and when I hit submit, nothing happens. It just reloads the page with no file selected. My guess from looking at the code is that for whatever reason, $xmlOut doesn't have a value saved to it. Any ideas?

**Comment by hatzopoulos** [comment]
This is just a fork, with no modifications. Please post your question to the author's repo here
https://github.com/samy/trillian-chat-history-converter

**Comment by JpTiger** [comment]
My mistake, sorry about that.
